name: Issue
description: Request ...
title: "New Request..."
labels: ["issue_test"]
body:
  - type: markdown
    attributes:
      value: |
        Request Contents
  - type: input
    id: extension_name
    attributes:
      label: Publsher & Extension Name
      description: Required.
      placeholder: "PUBLISHER.EXTENSIONS_NAME"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: version
      placeholder: 3.0.17
    validations:
      required: true
