name: Install Extension
description: Requesting the addition of a new extension to the private marketplace.
title: "[Open] Install Extension"
labels: ["initiating"]
body:
  - type: input
    id: extension_name
    attributes:
      label: Publsher & Extension Name
      description: Required.
      placeholder: "PUBLISHER.EXTENSIONS_NAME"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: version
      placeholder: 3.0.17
    validations:
      required: true